"""Add bot system models

Revision ID: 04434cc09ad7
Revises: ef9b820a4339
Create Date: 2025-12-26 23:54:59.059460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04434cc09ad7'
down_revision: Union[str, None] = 'ef9b820a4339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecommerce_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('SHOPIFY', 'WOOCOMMERCE', 'PRESTASHOP', 'CUSTOM', name='ecommerceprovider'), nullable=False),
    sa.Column('store_url', sa.String(), nullable=False),
    sa.Column('api_credentials', sa.JSON(), nullable=False),
    sa.Column('widget_settings', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ecommerce_configs_id'), 'ecommerce_configs', ['id'], unique=False)
    op.create_table('flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('nodes', sa.JSON(), nullable=False),
    sa.Column('edges', sa.JSON(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flows_id'), 'flows', ['id'], unique=False)
    op.add_column('bots', sa.Column('config', sa.JSON(), nullable=True))
    op.add_column('bots', sa.Column('flow_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bots', 'flows', ['flow_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bots', type_='foreignkey')
    op.drop_column('bots', 'flow_id')
    op.drop_column('bots', 'config')
    op.drop_index(op.f('ix_flows_id'), table_name='flows')
    op.drop_table('flows')
    op.drop_index(op.f('ix_ecommerce_configs_id'), table_name='ecommerce_configs')
    op.drop_table('ecommerce_configs')
    # ### end Alembic commands ###
