"""add_multi_tenancy_columns

Revision ID: 1d22504e76d2
Revises: ed7c7aeefcba
Create Date: 2025-12-22 18:55:12.163144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d22504e76d2'
down_revision: Union[str, None] = 'ed7c7aeefcba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('business_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bots', 'businesses', ['business_id'], ['id'])
    op.add_column('channels', sa.Column('business_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'channels', 'businesses', ['business_id'], ['id'])
    op.add_column('users', sa.Column('use_business', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'businesses', ['use_business'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'use_business')
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.drop_column('channels', 'business_id')
    op.drop_constraint(None, 'bots', type_='foreignkey')
    op.drop_column('bots', 'business_id')
    # ### end Alembic commands ###
