"""refactor_to_business_user_memberships

Revision ID: 2e636f163524
Revises: 1d22504e76d2
Create Date: 2025-12-22 18:59:37.923522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e636f163524'
down_revision: Union[str, None] = '1d22504e76d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_users', sa.Column('role', sa.String(), nullable=True))
    op.drop_constraint('users_use_business_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'use_business')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('use_business', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_use_business_fkey', 'users', 'businesses', ['use_business'], ['id'])
    op.drop_column('business_users', 'role')
    # ### end Alembic commands ###
