"""added_source_and_external_id_to_carts

Revision ID: 3098336b4bc4
Revises: 77f7511f8ba5
Create Date: 2026-01-03 20:23:02.807733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3098336b4bc4'
down_revision: Union[str, None] = '77f7511f8ba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_performance_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('intent_detected', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('response_source', sa.String(), nullable=False),
    sa.Column('ai_model_used', sa.String(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('user_phone', sa.String(), nullable=False),
    sa.Column('user_message', sa.String(), nullable=True),
    sa.Column('bot_response', sa.String(), nullable=True),
    sa.Column('led_to_cart_action', sa.Boolean(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_performance_metrics_business_id'), 'ai_performance_metrics', ['business_id'], unique=False)
    op.create_index(op.f('ix_ai_performance_metrics_id'), 'ai_performance_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_ai_performance_metrics_timestamp'), 'ai_performance_metrics', ['timestamp'], unique=False)
    op.create_index(op.f('ix_ai_performance_metrics_user_phone'), 'ai_performance_metrics', ['user_phone'], unique=False)
    op.create_table('customer_lifetime_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('user_phone', sa.String(), nullable=False),
    sa.Column('total_purchases', sa.Integer(), nullable=True),
    sa.Column('total_spent', sa.Float(), nullable=True),
    sa.Column('avg_order_value', sa.Float(), nullable=True),
    sa.Column('first_purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('days_since_last_purchase', sa.Integer(), nullable=True),
    sa.Column('carts_abandoned', sa.Integer(), nullable=True),
    sa.Column('carts_recovered', sa.Integer(), nullable=True),
    sa.Column('recovery_rate', sa.Float(), nullable=True),
    sa.Column('churn_risk_score', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_lifetime_values_business_id'), 'customer_lifetime_values', ['business_id'], unique=False)
    op.create_index(op.f('ix_customer_lifetime_values_id'), 'customer_lifetime_values', ['id'], unique=False)
    op.create_index(op.f('ix_customer_lifetime_values_user_phone'), 'customer_lifetime_values', ['user_phone'], unique=False)
    op.create_table('cart_recovery_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.Column('user_phone', sa.String(), nullable=False),
    sa.Column('event_type', sa.Enum('CART_CREATED', 'CART_ABANDONED', 'RECOVERY_SENT', 'CART_RECOVERED', 'CHECKOUT_COMPLETED', 'PAYMENT_COMPLETED', 'AI_FALLBACK', 'FAQ_HIT', 'LEARNING_SUGGESTION_CREATED', name='eventtype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('cart_value', sa.Float(), nullable=True),
    sa.Column('discount_code', sa.String(), nullable=True),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('time_to_recovery_hours', sa.Float(), nullable=True),
    sa.Column('recovery_channel', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_recovery_events_business_id'), 'cart_recovery_events', ['business_id'], unique=False)
    op.create_index(op.f('ix_cart_recovery_events_event_type'), 'cart_recovery_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_cart_recovery_events_id'), 'cart_recovery_events', ['id'], unique=False)
    op.create_index(op.f('ix_cart_recovery_events_timestamp'), 'cart_recovery_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_cart_recovery_events_user_phone'), 'cart_recovery_events', ['user_phone'], unique=False)
    op.add_column('carts', sa.Column('source', sa.String(), nullable=True))
    op.add_column('carts', sa.Column('external_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_carts_external_id'), 'carts', ['external_id'], unique=False)
    op.drop_column('carts', 'updated_at')
    op.drop_column('carts', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('carts', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_carts_external_id'), table_name='carts')
    op.drop_column('carts', 'external_id')
    op.drop_column('carts', 'source')
    op.drop_index(op.f('ix_cart_recovery_events_user_phone'), table_name='cart_recovery_events')
    op.drop_index(op.f('ix_cart_recovery_events_timestamp'), table_name='cart_recovery_events')
    op.drop_index(op.f('ix_cart_recovery_events_id'), table_name='cart_recovery_events')
    op.drop_index(op.f('ix_cart_recovery_events_event_type'), table_name='cart_recovery_events')
    op.drop_index(op.f('ix_cart_recovery_events_business_id'), table_name='cart_recovery_events')
    op.drop_table('cart_recovery_events')
    op.drop_index(op.f('ix_customer_lifetime_values_user_phone'), table_name='customer_lifetime_values')
    op.drop_index(op.f('ix_customer_lifetime_values_id'), table_name='customer_lifetime_values')
    op.drop_index(op.f('ix_customer_lifetime_values_business_id'), table_name='customer_lifetime_values')
    op.drop_table('customer_lifetime_values')
    op.drop_index(op.f('ix_ai_performance_metrics_user_phone'), table_name='ai_performance_metrics')
    op.drop_index(op.f('ix_ai_performance_metrics_timestamp'), table_name='ai_performance_metrics')
    op.drop_index(op.f('ix_ai_performance_metrics_id'), table_name='ai_performance_metrics')
    op.drop_index(op.f('ix_ai_performance_metrics_business_id'), table_name='ai_performance_metrics')
    op.drop_table('ai_performance_metrics')
    # ### end Alembic commands ###
