"""Add multi-platform ecommerce fields and magento provider

Revision ID: 47e17f5fbb1d
Revises: 58007878477c
Create Date: 2025-12-27 00:10:57.104428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47e17f5fbb1d'
down_revision: Union[str, None] = '58007878477c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('credentials', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_configs_id'), 'payment_configs', ['id'], unique=False)
    op.add_column('products', sa.Column('external_id', sa.String(), nullable=True))
    op.add_column('products', sa.Column('provider', sa.Enum('SHOPIFY', 'WOOCOMMERCE', 'PRESTASHOP', 'MAGENTO', 'CUSTOM', name='ecommerceprovider'), nullable=True))
    op.add_column('products', sa.Column('metadata_json', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_products_external_id'), 'products', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_external_id'), table_name='products')
    op.drop_column('products', 'metadata_json')
    op.drop_column('products', 'provider')
    op.drop_column('products', 'external_id')
    op.drop_index(op.f('ix_payment_configs_id'), table_name='payment_configs')
    op.drop_table('payment_configs')
    # ### end Alembic commands ###
