"""Add hybrid engine and payment config

Revision ID: 58007878477c
Revises: 04434cc09ad7
Create Date: 2025-12-27 00:03:18.569158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58007878477c'
down_revision: Union[str, None] = '04434cc09ad7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('hybrid_mode', sa.Boolean(), nullable=True))
    op.add_column('bots', sa.Column('rule_set', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'rule_set')
    op.drop_column('bots', 'hybrid_mode')
    # ### end Alembic commands ###
