"""fix_bot_channel_id

Revision ID: 60ddc48e653d
Revises: 5b226812ebe2
Create Date: 2025-12-29 15:20:27.094061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60ddc48e653d'
down_revision: Union[str, None] = '5b226812ebe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_channels', sa.Column('business_channel_id', sa.Integer(), nullable=True))
    op.drop_constraint('bot_channels_channel_id_fkey', 'bot_channels', type_='foreignkey')
    op.create_foreign_key(None, 'bot_channels', 'business_channels', ['business_channel_id'], ['id'], ondelete='CASCADE')
    op.drop_column('bot_channels', 'channel_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_channels', sa.Column('channel_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bot_channels', type_='foreignkey')
    op.create_foreign_key('bot_channels_channel_id_fkey', 'bot_channels', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    op.drop_column('bot_channels', 'business_channel_id')
    # ### end Alembic commands ###
