"""update user model3

Revision ID: 746d9d946bc5
Revises: e9b9b57d84b5
Create Date: 2025-12-20 14:39:43.128786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '746d9d946bc5'
down_revision: Union[str, None] = 'e9b9b57d84b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('code', sa.String(), nullable=True))
    op.drop_column('permissions', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('permissions', 'code')
    # ### end Alembic commands ###
