"""add_cart_metadata

Revision ID: 77f7511f8ba5
Revises: b2ac5b1a346c
Create Date: 2025-12-29 17:53:18.027327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77f7511f8ba5'
down_revision: Union[str, None] = 'b2ac5b1a346c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('metadata_json', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carts', 'metadata_json')
    # ### end Alembic commands ###
