"""Align models with frontend spec

Revision ID: 7ea43d3c2864
Revises: 47e17f5fbb1d
Create Date: 2025-12-27 14:42:45.605751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ea43d3c2864'
down_revision: Union[str, None] = '47e17f5fbb1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widget_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('welcome_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    op.create_index(op.f('ix_widget_configs_id'), 'widget_configs', ['id'], unique=False)
    op.add_column('business_channels', sa.Column('account_id', sa.String(), nullable=True))
    op.add_column('business_channels', sa.Column('token', sa.String(), nullable=True))
    op.add_column('business_channels', sa.Column('metadata_json', sa.JSON(), nullable=True))
    op.add_column('business_channels', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('ecommerce_configs', sa.Column('credentials', sa.JSON(), nullable=False))
    op.add_column('ecommerce_configs', sa.Column('active', sa.Boolean(), nullable=True))
    op.drop_column('ecommerce_configs', 'api_credentials')
    op.add_column('flows', sa.Column('viewport', sa.JSON(), nullable=True))
    op.add_column('flows', sa.Column('bot_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'flows', 'bots', ['bot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flows', type_='foreignkey')
    op.drop_column('flows', 'bot_id')
    op.drop_column('flows', 'viewport')
    op.add_column('ecommerce_configs', sa.Column('api_credentials', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('ecommerce_configs', 'active')
    op.drop_column('ecommerce_configs', 'credentials')
    op.drop_column('business_channels', 'active')
    op.drop_column('business_channels', 'metadata_json')
    op.drop_column('business_channels', 'token')
    op.drop_column('business_channels', 'account_id')
    op.drop_index(op.f('ix_widget_configs_id'), table_name='widget_configs')
    op.drop_table('widget_configs')
    # ### end Alembic commands ###
