"""update user model5

Revision ID: 7fab992f1480
Revises: a4dc8636dd0f
Create Date: 2025-12-20 18:06:41.798881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fab992f1480'
down_revision: Union[str, None] = 'a4dc8636dd0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('business_users_role_id_fkey', 'business_users', type_='foreignkey')
    op.drop_column('business_users', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_users', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('business_users_role_id_fkey', 'business_users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###
