"""update user model

Revision ID: aeb634d968fb
Revises: f173dfe9a8db
Create Date: 2025-12-20 13:19:20.122899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeb634d968fb'
down_revision: Union[str, None] = 'f173dfe9a8db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permissions', 'code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('roles', sa.Column('permissions', sa.JSON(), nullable=False))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('roles', 'permissions')
    op.alter_column('permissions', 'code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
