"""Add bot_type to bot

Revision ID: d2f07eaf1911
Revises: 086c7ade7366
Create Date: 2025-12-27 19:05:09.868366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2f07eaf1911'
down_revision: Union[str, None] = '086c7ade7366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('bot_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'bot_type')
    # ### end Alembic commands ###
