"""update user model2

Revision ID: e9b9b57d84b5
Revises: aeb634d968fb
Create Date: 2025-12-20 13:49:16.639308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9b9b57d84b5'
down_revision: Union[str, None] = 'aeb634d968fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('name', sa.String(), nullable=True))
    op.drop_constraint('permissions_code_key', 'permissions', type_='unique')
    op.drop_column('permissions', 'code')
    op.alter_column('role_permissions', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('role_permissions', 'permission_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    op.drop_column('roles', 'permissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permissions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.create_unique_constraint('roles_name_key', 'roles', ['name'])
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('role_permissions', 'permission_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('role_permissions', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('permissions', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('permissions_code_key', 'permissions', ['code'])
    op.drop_column('permissions', 'name')
    # ### end Alembic commands ###
