"""update user model5

Revision ID: ed7c7aeefcba
Revises: 7fab992f1480
Create Date: 2025-12-20 22:19:06.002999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed7c7aeefcba'
down_revision: Union[str, None] = '7fab992f1480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_channels', sa.Column('channel_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'business_channels', 'channels', ['channel_id'], ['id'])
    op.drop_column('business_channels', 'is_private')
    op.drop_column('business_channels', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_channels', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('business_channels', sa.Column('is_private', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'business_channels', type_='foreignkey')
    op.drop_column('business_channels', 'channel_id')
    # ### end Alembic commands ###
